/*
Copyright (c) Microsoft Corporation

All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in 
compliance with the License.  You may obtain a copy of the License 
at http://www.apache.org/licenses/LICENSE-2.0   


THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER 
EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF 
TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.  


See the Apache Version 2.0 License for specific language governing permissions and 
limitations under the License. 

*/

// DrExitCodes.h
//
// This file must contain *only* declarions of the form:
//
// DEFINE_DREXITCODE(name, value, description)
// DEFINE_DREXITCODE_NO_DESC(name, value)
// DECLARE_DREXITCODE(valname, description)
// DECLARE_DREXITCODE_NO_DESC(valname)
//
// It is included multiple times with different macro definitions.

// Values from ntstatus.h:
#define STATUS_NOT_SUPPORTED             ((DWORD)0xC00000BBL)
#define STATUS_UNHANDLED_EXCEPTION       ((DWORD)0xC0000144L)
//#define STATUS_ASSERTION_FAILURE         ((NTSTATUS)0xC0000420L)


DEFINE_DREXITCODE_NO_DESC(DrExitCode_OK, 0)
DEFINE_DREXITCODE_NO_DESC(DrExitCode_Fail, 1)
DEFINE_DREXITCODE_NO_DESC(DrExitCode_StillActive, STILL_ACTIVE)
DEFINE_DREXITCODE_NO_DESC(DrExitCode_Killed, (DrExitCode) STATUS_CONTROL_C_EXIT)
DEFINE_DREXITCODE_NO_DESC(DrExitCode_JobQuotaExceeded, ERROR_NOT_ENOUGH_QUOTA)

DECLARE_DREXITCODE_NO_DESC(STATUS_INVALID_HANDLE)
DECLARE_DREXITCODE_NO_DESC(STATUS_ACCESS_VIOLATION)
DECLARE_DREXITCODE_NO_DESC(STATUS_ARRAY_BOUNDS_EXCEEDED)
DECLARE_DREXITCODE_NO_DESC(STATUS_BREAKPOINT)
DECLARE_DREXITCODE_NO_DESC(STATUS_DATATYPE_MISALIGNMENT)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_DENORMAL_OPERAND)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_DIVIDE_BY_ZERO)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_INEXACT_RESULT)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_INVALID_OPERATION)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_MULTIPLE_FAULTS)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_MULTIPLE_TRAPS)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_OVERFLOW)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_STACK_CHECK)
DECLARE_DREXITCODE_NO_DESC(STATUS_FLOAT_UNDERFLOW)
DECLARE_DREXITCODE_NO_DESC(STATUS_GUARD_PAGE_VIOLATION)
DECLARE_DREXITCODE_NO_DESC(STATUS_ILLEGAL_INSTRUCTION)
DECLARE_DREXITCODE_NO_DESC(STATUS_IN_PAGE_ERROR)
DECLARE_DREXITCODE_NO_DESC(STATUS_INVALID_DISPOSITION)
DECLARE_DREXITCODE_NO_DESC(STATUS_INTEGER_DIVIDE_BY_ZERO)
DECLARE_DREXITCODE_NO_DESC(STATUS_INTEGER_OVERFLOW)
DECLARE_DREXITCODE_NO_DESC(STATUS_NONCONTINUABLE_EXCEPTION)
DECLARE_DREXITCODE_NO_DESC(STATUS_NOT_SUPPORTED)
DECLARE_DREXITCODE_NO_DESC(STATUS_PRIVILEGED_INSTRUCTION)
DECLARE_DREXITCODE_NO_DESC(STATUS_REG_NAT_CONSUMPTION)
DECLARE_DREXITCODE_NO_DESC(STATUS_SINGLE_STEP)
DECLARE_DREXITCODE_NO_DESC(STATUS_STACK_OVERFLOW)
DECLARE_DREXITCODE_NO_DESC(STATUS_ASSERTION_FAILURE)
DECLARE_DREXITCODE_NO_DESC(STATUS_UNHANDLED_EXCEPTION)

