/*
Copyright (c) Microsoft Corporation

All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in 
compliance with the License.  You may obtain a copy of the License 
at http://www.apache.org/licenses/LICENSE-2.0   


THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER 
EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF 
TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.  


See the Apache Version 2.0 License for specific language governing permissions and 
limitations under the License. 

*/

// This file must consist only of DECLARE_DRPROPERTYTYPE statements

DECLARE_DRPROPERTYTYPE(Unknown)
DECLARE_DRPROPERTYTYPE(Boolean)
DECLARE_DRPROPERTYTYPE(Int16)
DECLARE_DRPROPERTYTYPE(Int32)
DECLARE_DRPROPERTYTYPE(Int64)
DECLARE_DRPROPERTYTYPE(UInt16)
DECLARE_DRPROPERTYTYPE(UInt32)
DECLARE_DRPROPERTYTYPE(UInt64)
DECLARE_DRPROPERTYTYPE(Double)
DECLARE_DRPROPERTYTYPE(HexUInt16)
DECLARE_DRPROPERTYTYPE(HexUInt32)
DECLARE_DRPROPERTYTYPE(HexUInt64)
DECLARE_DRPROPERTYTYPE(String)
DECLARE_DRPROPERTYTYPE(Guid)
DECLARE_DRPROPERTYTYPE(TimeStamp)
DECLARE_DRPROPERTYTYPE(TimeInterval)
DECLARE_DRPROPERTYTYPE(BeginTag)
DECLARE_DRPROPERTYTYPE(EndTag)
DECLARE_DRPROPERTYTYPE(DrError)
DECLARE_DRPROPERTYTYPE(DrExitCode)
DECLARE_DRPROPERTYTYPE(Blob)
DECLARE_DRPROPERTYTYPE(Payload)
DECLARE_DRPROPERTYTYPE(EnvironmentBlock)
DECLARE_DRPROPERTYTYPE(PropertyList)
DECLARE_DRPROPERTYTYPE(TagIdValue)

DECLARE_DRPROPERTYTYPE(AppendExtentOptions)
DECLARE_DRPROPERTYTYPE(AppendBlockOptions)
DECLARE_DRPROPERTYTYPE(SyncOptions)
DECLARE_DRPROPERTYTYPE(SyncDirectiveOptions)
DECLARE_DRPROPERTYTYPE(ReadExtentOptions)
DECLARE_DRPROPERTYTYPE(AppendStreamOptions)
DECLARE_DRPROPERTYTYPE(EnumDirectoryOptions)
DECLARE_DRPROPERTYTYPE(EnInfoBits)
DECLARE_DRPROPERTYTYPE(UpdateExtentMetadataOptions)
DECLARE_DRPROPERTYTYPE(StreamInfoBits)
DECLARE_DRPROPERTYTYPE(StreamCapabilityBits)
DECLARE_DRPROPERTYTYPE(ExtentInfoBits)
DECLARE_DRPROPERTYTYPE(ExtentInstanceInfoBits)
DECLARE_DRPROPERTYTYPE(FailureInjectionOptions)

