//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DryadLinq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DryadLinq.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: AddVertexMethod on {0} not handled..
        /// </summary>
        internal static string AddVertexNotHandled {
            get {
                return ResourceManager.GetString("AddVertexNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate: No elements..
        /// </summary>
        internal static string AggregateNoElements {
            get {
                return ResourceManager.GetString("AggregateNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate operator {0} is not supported..
        /// </summary>
        internal static string AggregateOperatorNotSupported {
            get {
                return ResourceManager.GetString("AggregateOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation operator &apos;{0}&apos; can only work on objects that implement IComparable..
        /// </summary>
        internal static string AggregationOperatorRequiresIComparable {
            get {
                return ResourceManager.GetString("AggregationOperatorRequiresIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This query instance has already been submitted. To submit a query more than once, create a new IQueryable&lt;&gt; instance..
        /// </summary>
        internal static string AlreadySubmitted {
            get {
                return ResourceManager.GetString("AlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A query instance has already been submitted. To submit a query more than once, create a new IQueryable&lt;&gt; instance..
        /// </summary>
        internal static string AlreadySubmittedInMaterialize {
            get {
                return ResourceManager.GetString("AlreadySubmittedInMaterialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of array {0} must be greater than or equal to {1} ({2} + {3})..
        /// </summary>
        internal static string ArrayLengthVsCountAndOffset {
            get {
                return ResourceManager.GetString("ArrayLengthVsCountAndOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method tagged [Associative] should take two parameters of type T and return type T. Method={0}..
        /// </summary>
        internal static string AssociativeMethodHasWrongForm {
            get {
                return ResourceManager.GetString("AssociativeMethodHasWrongForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative class must have a public parameterless constructor. Class={0}..
        /// </summary>
        internal static string AssociativeTypeDoesNotHavePublicDefaultCtor {
            get {
                return ResourceManager.GetString("AssociativeTypeDoesNotHavePublicDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative class must implement IDecomposable&lt;,,&gt; or IDecomposableRecursive&lt;,,&gt;.  Class={0}..
        /// </summary>
        internal static string AssociativeTypeDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("AssociativeTypeDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative class should implement only one IAssociativeRecursive interface. Class={0}..
        /// </summary>
        internal static string AssociativeTypeImplementsTooManyInterfaces {
            get {
                return ResourceManager.GetString("AssociativeTypeImplementsTooManyInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative class must be public.  Class={0}..
        /// </summary>
        internal static string AssociativeTypeMustBePublic {
            get {
                return ResourceManager.GetString("AssociativeTypeMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative class types must match the function that it decorates. Method={0}. Class={1}..
        /// </summary>
        internal static string AssociativeTypesDoNotMatch {
            get {
                return ResourceManager.GetString("AssociativeTypesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A LINQ to HPC query that is submitted should involve at least one operator..
        /// </summary>
        internal static string AtLeastOneOperatorRequired {
            get {
                return ResourceManager.GetString("AtLeastOneOperatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to read from a stream that was opened for writing..
        /// </summary>
        internal static string AttemptToReadFromAWriteStream {
            get {
                return ResourceManager.GetString("AttemptToReadFromAWriteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: The auto-generated LINQ to HPC vertex assembly was missing..
        /// </summary>
        internal static string AutogeneratedAssemblyMissing {
            get {
                return ResourceManager.GetString("AutogeneratedAssemblyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average: No elements.
        /// </summary>
        internal static string AverageNoElements {
            get {
                return ResourceManager.GetString("AverageNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of separators passed to AssumeRangePartition must equal src.nPartitions - 1. nRangeSeparators={0}, Expected={1}..
        /// </summary>
        internal static string BadSeparatorCount {
            get {
                return ResourceManager.GetString("BadSeparatorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job cannot be submitted because either the client program or one of its dependencies is targetted for 32 bit execution ({0}). To correct this problem make sure your binaries are compiled as &apos;x64&apos; or &apos;AnyCPU&apos;..
        /// </summary>
        internal static string Binaries32BitNotSupported {
            get {
                return ResourceManager.GetString("Binaries32BitNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch {0} of Fork is not used..
        /// </summary>
        internal static string BranchOfForkNotUsed {
            get {
                return ResourceManager.GetString("BranchOfForkNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error processing anonymous type in query..
        /// </summary>
        internal static string BugInHandlingAnonymousClass {
            get {
                return ResourceManager.GetString("BugInHandlingAnonymousClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access path {0}.
        /// </summary>
        internal static string CannotAccesFilePath {
            get {
                return ResourceManager.GetString("CannotAccesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t add Tee to a node with more than one outputs..
        /// </summary>
        internal static string CannotAddTeeToNode {
            get {
                return ResourceManager.GetString("CannotAddTeeToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: cannot attach a pipeline.
        /// </summary>
        internal static string CannotAttach {
            get {
                return ResourceManager.GetString("CannotAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: cannot be empty.
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t be used for reference type..
        /// </summary>
        internal static string CannotBeUsedForReferenceType {
            get {
                return ResourceManager.GetString("CannotBeUsedForReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t call on PartitionInfo of type {0}.
        /// </summary>
        internal static string CannotCallPartitionInfoOnType {
            get {
                return ResourceManager.GetString("CannotCallPartitionInfoOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t concat two datasets with different compression schemes..
        /// </summary>
        internal static string CannotConcatDatasetsWithDifferentCompression {
            get {
                return ResourceManager.GetString("CannotConcatDatasetsWithDifferentCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t create partition node based on random partition..
        /// </summary>
        internal static string CannotCreatePartitionNodeRandom {
            get {
                return ResourceManager.GetString("CannotCreatePartitionNodeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create multiple tables with different compression schemes..
        /// </summary>
        internal static string CannotCreateTablesWithDifferentCompression {
            get {
                return ResourceManager.GetString("CannotCreateTablesWithDifferentCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for types containing circular references. Type = {0}..
        /// </summary>
        internal static string CannotHandleCircularTypes {
            get {
                return ResourceManager.GetString("CannotHandleCircularTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for type {0} because it derives from the non-primitive type {1}. Consider using a custom serializer for {0}. Please note this auto-serialization rule may have exceptions for built-in types. Please see product documentation for details..
        /// </summary>
        internal static string CannotHandleDerivedtypes {
            get {
                return ResourceManager.GetString("CannotHandleDerivedtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for types containing fields of System.Object, System.Object[] or other collections of System.Object. Type = {0}..
        /// </summary>
        internal static string CannotHandleObjectFields {
            get {
                return ResourceManager.GetString("CannotHandleObjectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for type that has subtypes or derives from a non-primitive type. Type = {0}..
        /// </summary>
        internal static string CannotHandleSubtypes {
            get {
                return ResourceManager.GetString("CannotHandleSubtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t have more than one output channel..
        /// </summary>
        internal static string CannotHaveMoreThanOneOutput {
            get {
                return ResourceManager.GetString("CannotHaveMoreThanOneOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read query plan for job: {0}..
        /// </summary>
        internal static string CannotReadQueryPlan {
            get {
                return ResourceManager.GetString("CannotReadQueryPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: cannot rebuild optimized query expression for node..
        /// </summary>
        internal static string CannotRebuildOptimizedQueryExpression {
            get {
                return ResourceManager.GetString("CannotRebuildOptimizedQueryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Cannot reset this IEnumerator..
        /// </summary>
        internal static string CannotResetIEnumerator {
            get {
                return ResourceManager.GetString("CannotResetIEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HpcLinqQuery IQueryable objects cannot be added to object store..
        /// </summary>
        internal static string CannotSerializeHpcLinqQuery {
            get {
                return ResourceManager.GetString("CannotSerializeHpcLinqQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize object store due to non-serializable object. Type = {0}..
        /// </summary>
        internal static string CannotSerializeObject {
            get {
                return ResourceManager.GetString("CannotSerializeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A LINQ to HPC channel cannot be read more than once. For example, the delegate in Apply() may only enumerate its input once..
        /// </summary>
        internal static string ChannelCannotBeReadMoreThanOnce {
            get {
                return ResourceManager.GetString("ChannelCannotBeReadMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ClusterName configuration must be set to the name of a Windows HPC Server head node..
        /// </summary>
        internal static string ClusterNameMustBeSpecified {
            get {
                return ResourceManager.GetString("ClusterNameMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not a LineRecord..
        /// </summary>
        internal static string CompareArgIncorrect {
            get {
                return ResourceManager.GetString("CompareArgIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a comparer expression is not provided, TElement must implement IEquatable or override both Equals() and GetHashCode(). TElement={0}..
        /// </summary>
        internal static string ComparerExpressionMustBeSpecifiedOrElementTypeMustBeIEquatable {
            get {
                return ResourceManager.GetString("ComparerExpressionMustBeSpecifiedOrElementTypeMustBeIEquatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a key-comparer is not provided, TKey must implement IComparable. TKey={0}..
        /// </summary>
        internal static string ComparerMustBeSpecifiedOrKeyTypeMustBeIComparable {
            get {
                return ResourceManager.GetString("ComparerMustBeSpecifiedOrKeyTypeMustBeIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a key-comparer is not provided, TKey must override GetHashCode() and either implement IEquatable or override Equals(). TKey={0}..
        /// </summary>
        internal static string ComparerMustBeSpecifiedOrKeyTypeMustBeIEquatable {
            get {
                return ResourceManager.GetString("ComparerMustBeSpecifiedOrKeyTypeMustBeIEquatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration object is read-only..
        /// </summary>
        internal static string ConfigReadonly {
            get {
                return ResourceManager.GetString("ConfigReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HpcLinqContext has been disposed..
        /// </summary>
        internal static string ContextDisposed {
            get {
                return ResourceManager.GetString("ContextDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get version information for HpcLinq client component. See inner exception..
        /// </summary>
        internal static string CouldNotGetClientVersion {
            get {
                return ResourceManager.GetString("CouldNotGetClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get version information for HpcLinq server component. See inner exception..
        /// </summary>
        internal static string CouldNotGetServerVersion {
            get {
                return ResourceManager.GetString("CouldNotGetServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating DSC data from local debug mode. See inner exception for details..
        /// </summary>
        internal static string CreatingDscDataFromLocalDebugFailed {
            get {
                return ResourceManager.GetString("CreatingDscDataFromLocalDebugFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom serializer type must either be a class or a struct that implements IHpcSerializer({1}). Type = {0}.
        /// </summary>
        internal static string CustomSerializerMustBeClassOrStruct {
            get {
                return ResourceManager.GetString("CustomSerializerMustBeClassOrStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom serializer type must have a public default constructor. Type = {0}..
        /// </summary>
        internal static string CustomSerializerMustSupportDefaultCtor {
            get {
                return ResourceManager.GetString("CustomSerializerMustSupportDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomposition class must have a public parameterless constructor. Class={0}..
        /// </summary>
        internal static string DecomposerTypeDoesNotHavePublicDefaultCtor {
            get {
                return ResourceManager.GetString("DecomposerTypeDoesNotHavePublicDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomposition class must implement IDecomposable&lt;,,&gt; or IDecomposableRecursive&lt;,,&gt;.  Class={0}..
        /// </summary>
        internal static string DecomposerTypeDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("DecomposerTypeDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomposition class should implement only one decomposable interface. Class={0}..
        /// </summary>
        internal static string DecomposerTypeImplementsTooManyInterfaces {
            get {
                return ResourceManager.GetString("DecomposerTypeImplementsTooManyInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomposition class must be public.  Class={0}..
        /// </summary>
        internal static string DecomposerTypeMustBePublic {
            get {
                return ResourceManager.GetString("DecomposerTypeMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomposition class types must match the function that it decorates. Method={0}. Class={1}..
        /// </summary>
        internal static string DecomposerTypesDoNotMatch {
            get {
                return ResourceManager.GetString("DecomposerTypesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job did not complete successfully. Refer to HPC Cluster Manager and/or HPC APIs for more detail..
        /// </summary>
        internal static string DidNotCompleteSuccessfully {
            get {
                return ResourceManager.GetString("DidNotCompleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistinctAttribute: Comparer {0} is not defined..
        /// </summary>
        internal static string DistinctAttributeComparerNotDefined {
            get {
                return ResourceManager.GetString("DistinctAttributeComparerNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: The Distinct operator can only take at most 2 arguments..
        /// </summary>
        internal static string DistinctOnlyTakesTwoArgs {
            get {
                return ResourceManager.GetString("DistinctOnlyTakesTwoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DryadLINQ requires the DRYAD_HOME environment variable to be set to the Dryad binary folder..
        /// </summary>
        internal static string DryadHomeMustBeSpecified {
            get {
                return ResourceManager.GetString("DryadHomeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSC fileset error: {0}..
        /// </summary>
        internal static string DSCStreamError {
            get {
                return ResourceManager.GetString("DSCStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Cannot have dynamic manager of type {0}..
        /// </summary>
        internal static string DynamicManagerType {
            get {
                return ResourceManager.GetString("DynamicManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read failure: End of stream encountered while reading {0}. Data may be corrupt or does not match the file set compression scheme..
        /// </summary>
        internal static string EndOfStreamEncountered {
            get {
                return ResourceManager.GetString("EndOfStreamEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading metadata..
        /// </summary>
        internal static string ErrorReadingMetadata {
            get {
                return ResourceManager.GetString("ErrorReadingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing metadata..
        /// </summary>
        internal static string ErrorWritingMetadata {
            get {
                return ResourceManager.GetString("ErrorWritingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must be a method call: [{0}]..
        /// </summary>
        internal static string ExpressionMustBeMethodCall {
            get {
                return ResourceManager.GetString("ExpressionMustBeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot handle expression of type {1}..
        /// </summary>
        internal static string ExpressionTypeNotHandled {
            get {
                return ResourceManager.GetString("ExpressionTypeNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to allocate a new native data block of size {0}..
        /// </summary>
        internal static string FailedToAllocateNewNativeBuffer {
            get {
                return ResourceManager.GetString("FailedToAllocateNewNativeBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build {0}. See the client side log ({1}) for compilation error messages..
        /// </summary>
        internal static string FailedToBuild {
            get {
                return ResourceManager.GetString("FailedToBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create DSC fileset: {0}..
        /// </summary>
        internal static string FailedToCreateStream {
            get {
                return ResourceManager.GetString("FailedToCreateStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize object from object store..
        /// </summary>
        internal static string FailedToDeserialize {
            get {
                return ResourceManager.GetString("FailedToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get read paths for DSC fileset {0}..
        /// </summary>
        internal static string FailedToGetReadPathsForStream {
            get {
                return ResourceManager.GetString("FailedToGetReadPathsForStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get stream properties for file set {0}..
        /// </summary>
        internal static string FailedToGetStreamProps {
            get {
                return ResourceManager.GetString("FailedToGetStreamProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native channel failed to read from input channel at port {0}. Win32 error = {1}..
        /// </summary>
        internal static string FailedToReadFromInputChannel {
            get {
                return ResourceManager.GetString("FailedToReadFromInputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Failed to remove the Merge node..
        /// </summary>
        internal static string FailedToRemoveMergeNode {
            get {
                return ResourceManager.GetString("FailedToRemoveMergeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native channel failed to write to output channel at port {0}..
        /// </summary>
        internal static string FailedToWriteToOutputChannel {
            get {
                return ResourceManager.GetString("FailedToWriteToOutputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in Distinct..
        /// </summary>
        internal static string FailureInDistinct {
            get {
                return ResourceManager.GetString("FailureInDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure during Except..
        /// </summary>
        internal static string FailureInExcept {
            get {
                return ResourceManager.GetString("FailureInExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in hash based GroupBy..
        /// </summary>
        internal static string FailureInHashGroupBy {
            get {
                return ResourceManager.GetString("FailureInHashGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in hash based GroupJoin..
        /// </summary>
        internal static string FailureInHashGroupJoin {
            get {
                return ResourceManager.GetString("FailureInHashGroupJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in hash based Join..
        /// </summary>
        internal static string FailureInHashJoin {
            get {
                return ResourceManager.GetString("FailureInHashJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure during Intersect..
        /// </summary>
        internal static string FailureInIntersect {
            get {
                return ResourceManager.GetString("FailureInIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in {0}..
        /// </summary>
        internal static string FailureInOperator {
            get {
                return ResourceManager.GetString("FailureInOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in ordered GroupBy..
        /// </summary>
        internal static string FailureInOrderedGroupBy {
            get {
                return ResourceManager.GetString("FailureInOrderedGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure during sorting..
        /// </summary>
        internal static string FailureInSort {
            get {
                return ResourceManager.GetString("FailureInSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in sort based GroupBy..
        /// </summary>
        internal static string FailureInSortGroupBy {
            get {
                return ResourceManager.GetString("FailureInSortGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply: Failure in user-defined function..
        /// </summary>
        internal static string FailureInUserApplyFunction {
            get {
                return ResourceManager.GetString("FailureInUserApplyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open FileSet and/or read its properties..
        /// </summary>
        internal static string FileSetCouldNotBeOpened {
            get {
                return ResourceManager.GetString("FileSetCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSet must be sealed before calling FromDsc()..
        /// </summary>
        internal static string FileSetMustBeSealed {
            get {
                return ResourceManager.GetString("FileSetMustBeSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSet must have at least one file..
        /// </summary>
        internal static string FileSetMustHaveAtLeastOneFile {
            get {
                return ResourceManager.GetString("FileSetMustHaveAtLeastOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint was disabled..
        /// </summary>
        internal static string FingerprintDisabled {
            get {
                return ResourceManager.GetString("FingerprintDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First: No elements..
        /// </summary>
        internal static string FirstNoElementsFirst {
            get {
                return ResourceManager.GetString("FirstNoElementsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error serializing object store. See inner exception..
        /// </summary>
        internal static string GeneralSerializeFailure {
            get {
                return ResourceManager.GetString("GeneralSerializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error returned from GetFileSizeEx: {0}..
        /// </summary>
        internal static string GetFileSizeError {
            get {
                return ResourceManager.GetString("GetFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFP() is not implemented for this stream type..
        /// </summary>
        internal static string GetFPNotSupported {
            get {
                return ResourceManager.GetString("GetFPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetURI() is not implemented for this stream type..
        /// </summary>
        internal static string GetURINotSupported {
            get {
                return ResourceManager.GetString("GetURINotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inputs to homomorphic apply must have same number of input partitions.
        /// </summary>
        internal static string HomomorphicApplyNeedsSamePartitionCount {
            get {
                return ResourceManager.GetString("HomomorphicApplyNeedsSamePartitionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobMinNodes must be greater than 1..
        /// </summary>
        internal static string HpcLinqJobMinMustBe2OrMore {
            get {
                return ResourceManager.GetString("HpcLinqJobMinMustBe2OrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string HpcLinqStringDictionaryReadonly {
            get {
                return ResourceManager.GetString("HpcLinqStringDictionaryReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Illegal type of dynamic manager in dynamic node.
        /// </summary>
        internal static string IllegalDynamicManagerType {
            get {
                return ResourceManager.GetString("IllegalDynamicManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI is not well formed: {0}.
        /// </summary>
        internal static string IllFormedUri {
            get {
                return ResourceManager.GetString("IllFormedUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments in the table URI are not well formed..
        /// </summary>
        internal static string IllFormedUriArguments {
            get {
                return ResourceManager.GetString("IllFormedUriArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of range..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index overflowed range of Int32..
        /// </summary>
        internal static string IndexTooSmall {
            get {
                return ResourceManager.GetString("IndexTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: InputArity must equal Children.Length..
        /// </summary>
        internal static string InputArityMustEqualChildren {
            get {
                return ResourceManager.GetString("InputArityMustEqualChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input expression must be a LINQ to HPC source..
        /// </summary>
        internal static string InputMustBeHpcLinqSource {
            get {
                return ResourceManager.GetString("InputMustBeHpcLinqSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data type cannot be an anonymous type..
        /// </summary>
        internal static string InputTypeCannotBeAnonymous {
            get {
                return ResourceManager.GetString("InputTypeCannotBeAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Can&apos;t be used for value type..
        /// </summary>
        internal static string Internal_CannotBeUsedForValueType {
            get {
                return ResourceManager.GetString("Internal_CannotBeUsedForValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments &apos;partitionKeys&apos; and &apos;isDescending&apos; are inconsistent..
        /// </summary>
        internal static string IsDescendingIsInconsistent {
            get {
                return ResourceManager.GetString("IsDescendingIsInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobOption({0}, {1}) not implemented..
        /// </summary>
        internal static string JobOptionNotImplemented {
            get {
                return ResourceManager.GetString("JobOptionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated server error when querying job status..
        /// </summary>
        internal static string JobStatusQueryError {
            get {
                return ResourceManager.GetString("JobStatusQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job to create this HpcLinqQuery(T) failed with error: {0}..
        /// </summary>
        internal static string JobToCreateTableFailed {
            get {
                return ResourceManager.GetString("JobToCreateTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job to create this HpcLinqQuery(T) was canceled by the user..
        /// </summary>
        internal static string JobToCreateTableWasCanceled {
            get {
                return ResourceManager.GetString("JobToCreateTableWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found in collection..
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last: No elements..
        /// </summary>
        internal static string LastNoElements {
            get {
                return ResourceManager.GetString("LastNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: No elements.
        /// </summary>
        internal static string MaxNoElements {
            get {
                return ResourceManager.GetString("MaxNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordType does not match with file set metadata.  Use FromDsc&lt;T&gt; with matching T, or an overload that supresses type-check. RecordType={0}, DscStream.recordType={1}..
        /// </summary>
        internal static string MetadataRecordType {
            get {
                return ResourceManager.GetString("MetadataRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min: No elements.
        /// </summary>
        internal static string MinNoElements {
            get {
                return ResourceManager.GetString("MinNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access file {0}, which is part of DSC stream {1}. If this file has other replicas, they were all attempted but could not be accessed either..
        /// </summary>
        internal static string MultiBlockCannotAccesFilePath {
            get {
                return ResourceManager.GetString("MultiBlockCannotAccesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partition list of the table was empty..
        /// </summary>
        internal static string MultiBlockEmptyPartitionList {
            get {
                return ResourceManager.GetString("MultiBlockEmptyPartitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple query outputs are targeted to the same DSC fileset name {0}.
        /// </summary>
        internal static string MultipleOutputsWithSameDscUri {
            get {
                return ResourceManager.GetString("MultipleOutputsWithSameDscUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key out of range..
        /// </summary>
        internal static string MultiQueryableKeyOutOfRange {
            get {
                return ResourceManager.GetString("MultiQueryableKeyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Must specify the file name for the output assembly..
        /// </summary>
        internal static string MustSpecifyOutputAssemblyFileName {
            get {
                return ResourceManager.GetString("MustSpecifyOutputAssemblyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query must be created from a HpcLinqContext object and only use LINQ to HPC operators..
        /// </summary>
        internal static string MustStartFromContext {
            get {
                return ResourceManager.GetString("MustStartFromContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Negative length in memcopy..
        /// </summary>
        internal static string NegativeLengthInMemcopy {
            get {
                return ResourceManager.GetString("NegativeLengthInMemcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sources[{0}] is not a LINQ to HPC query. A LINQ to HPC IQueryable should be created via an HpcLinqContext object and use only LINQ to HPC operators..
        /// </summary>
        internal static string NotAHpcLinqQuery {
            get {
                return ResourceManager.GetString("NotAHpcLinqQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeySelector function must be non-null..
        /// </summary>
        internal static string NullKeySelector {
            get {
                return ResourceManager.GetString("NullKeySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: The result and element selectors must be non-null.
        /// </summary>
        internal static string NullSelector {
            get {
                return ResourceManager.GetString("NullSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork: The number of keys must match the number of output ports..
        /// </summary>
        internal static string NumberOfKeysMustEqualNumOutputPorts {
            get {
                return ResourceManager.GetString("NumberOfKeysMustEqualNumOutputPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of keys must be equal to PartitionCount-1..
        /// </summary>
        internal static string NumKeys {
            get {
                return ResourceManager.GetString("NumKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property only available for physical data..
        /// </summary>
        internal static string OnlyAvailableForPhysicalData {
            get {
                return ResourceManager.GetString("OnlyAvailableForPhysicalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: OpenForWrite called when fs was not null..
        /// </summary>
        internal static string OpenForWriteError {
            get {
                return ResourceManager.GetString("OpenForWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; encountered in expression isn&apos;t a valid LINQ to HPC operator..
        /// </summary>
        internal static string OperatorNotSupported {
            get {
                return ResourceManager.GetString("OperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output data type cannot be an anonymous type..
        /// </summary>
        internal static string OutputTypeCannotBeAnonymous {
            get {
                return ResourceManager.GetString("OutputTypeCannotBeAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output DSC fileset name {0} is also used as the query source or as one of the referenced data sources..
        /// </summary>
        internal static string OutputUriAlsoQueryInput {
            get {
                return ResourceManager.GetString("OutputUriAlsoQueryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partition count must be greater than 0..
        /// </summary>
        internal static string PartitionCountMustBePositive {
            get {
                return ResourceManager.GetString("PartitionCountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return value of partitionFunc exceeded the number of ports..
        /// </summary>
        internal static string PartitionFuncReturnValueExceedsNumPorts {
            get {
                return ResourceManager.GetString("PartitionFuncReturnValueExceedsNumPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided range-partition keys are not consistenly ascending or descending..
        /// </summary>
        internal static string PartitionKeysAreNotConsistentlyOrdered {
            get {
                return ResourceManager.GetString("PartitionKeysAreNotConsistentlyOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partition keys are not provided..
        /// </summary>
        internal static string PartitionKeysNotProvided {
            get {
                return ResourceManager.GetString("PartitionKeysNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each partition needs at least {0} records for this sliding window computation..
        /// </summary>
        internal static string PartitionTooSmallForSlidingWindow {
            get {
                return ResourceManager.GetString("PartitionTooSmallForSlidingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is not supported..
        /// </summary>
        internal static string PositionNotSupported {
            get {
                return ResourceManager.GetString("PositionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix {0} has already been used for another provider..
        /// </summary>
        internal static string PrefixAlreadyUsedForOtherProvider {
            get {
                return ResourceManager.GetString("PrefixAlreadyUsedForOtherProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangePartition: partition keys and output channels mismatch. There were {0} keys and {1} channels..
        /// </summary>
        internal static string RangePartitionInputOutputMismatch {
            get {
                return ResourceManager.GetString("RangePartitionInputOutputMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangePartition: partition keys are missing..
        /// </summary>
        internal static string RangePartitionKeysMissing {
            get {
                return ResourceManager.GetString("RangePartitionKeysMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native channel error while reading from file. Win32 error code = {0}..
        /// </summary>
        internal static string ReadFileError {
            get {
                return ResourceManager.GetString("ReadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read is not supported..
        /// </summary>
        internal static string ReadNotAllowed {
            get {
                return ResourceManager.GetString("ReadNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadWrite access is not supported..
        /// </summary>
        internal static string ReadWriteNotSupported {
            get {
                return ResourceManager.GetString("ReadWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum record size is 2GB..
        /// </summary>
        internal static string RecordSizeMax2GB {
            get {
                return ResourceManager.GetString("RecordSizeMax2GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A query instance appears more than once in &apos;sources&apos;. A query instance should be submitted at most once. To submit a query more than once, create a new IQueryable&lt;&gt; instance..
        /// </summary>
        internal static string SameQuerySubmittedMultipleTimesInMaterialize {
            get {
                return ResourceManager.GetString("SameQuerySubmittedMultipleTimesInMaterialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek is not supported..
        /// </summary>
        internal static string SeekNotSupported {
            get {
                return ResourceManager.GetString("SeekNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceEqual() is not supported..
        /// </summary>
        internal static string SequenceEqualNotSupported {
            get {
                return ResourceManager.GetString("SequenceEqualNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomHpcSerializer attribute for type {0} does not define a SerializerType..
        /// </summary>
        internal static string SerializerTypeMustBeNonNull {
            get {
                return ResourceManager.GetString("SerializerTypeMustBeNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} referred to by CustomHpcSerializer attribute must implement IHpcSerializer({1})..
        /// </summary>
        internal static string SerializerTypeMustSupportIHpcSerializer {
            get {
                return ResourceManager.GetString("SerializerTypeMustSupportIHpcSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetCalcFP() is not implemented for this stream type..
        /// </summary>
        internal static string SetCalcFPNotSupported {
            get {
                return ResourceManager.GetString("SetCalcFPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetLength is not supported..
        /// </summary>
        internal static string SetLengthNotSupported {
            get {
                return ResourceManager.GetString("SetLengthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position_Set is not supported..
        /// </summary>
        internal static string SettingPositionNotSupported {
            get {
                return ResourceManager.GetString("SettingPositionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: should not create vertex code for Concat..
        /// </summary>
        internal static string ShouldNotCreateCodeForConcat {
            get {
                return ResourceManager.GetString("ShouldNotCreateCodeForConcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: should not create vertex code for a dummy node..
        /// </summary>
        internal static string ShouldNotCreateCodeForDummyNode {
            get {
                return ResourceManager.GetString("ShouldNotCreateCodeForDummyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: should not create vertex code for input..
        /// </summary>
        internal static string ShouldNotCreateCodeForInput {
            get {
                return ResourceManager.GetString("ShouldNotCreateCodeForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: should not create vertex code for output..
        /// </summary>
        internal static string ShouldNotCreateCodeForOutput {
            get {
                return ResourceManager.GetString("ShouldNotCreateCodeForOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: should not create vertex code for Tee..
        /// </summary>
        internal static string ShouldNotCreateCodeForTee {
            get {
                return ResourceManager.GetString("ShouldNotCreateCodeForTee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Should never call Reset().
        /// </summary>
        internal static string ShouldNototCallReset {
            get {
                return ResourceManager.GetString("ShouldNototCallReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single: More than one element..
        /// </summary>
        internal static string SingleMoreThanOneElement {
            get {
                return ResourceManager.GetString("SingleMoreThanOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single: No elements..
        /// </summary>
        internal static string SingleNoElements {
            get {
                return ResourceManager.GetString("SingleNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Sorted chunk cannot be empty..
        /// </summary>
        internal static string SortedChunkCannotBeEmpty {
            get {
                return ResourceManager.GetString("SortedChunkCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: source must be DryadVertexReader..
        /// </summary>
        internal static string SourceMustBeDryadVertexReader {
            get {
                return ResourceManager.GetString("SourceMustBeDryadVertexReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source is not ordered..
        /// </summary>
        internal static string SourceNotOrdered {
            get {
                return ResourceManager.GetString("SourceNotOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source for mergesort must be of type IMultiEnumerable..
        /// </summary>
        internal static string SourceOfMergesortMustBeMultiEnumerable {
            get {
                return ResourceManager.GetString("SourceOfMergesortMustBeMultiEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSC fileset already exists: {0}..
        /// </summary>
        internal static string StreamAlreadyExists {
            get {
                return ResourceManager.GetString("StreamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DSC fileset {0} doesn&apos;t exist..
        /// </summary>
        internal static string StreamDoesNotExist {
            get {
                return ResourceManager.GetString("StreamDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error submitting job to {0}. Refer to inner exception for more detail..
        /// </summary>
        internal static string SubmissionFailure {
            get {
                return ResourceManager.GetString("SubmissionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only DSC URIs are supported..
        /// </summary>
        internal static string TargetMustBeDscUri {
            get {
                return ResourceManager.GetString("TargetMustBeDscUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThenBy is not supported..
        /// </summary>
        internal static string ThenByNotSupported {
            get {
                return ResourceManager.GetString("ThenByNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries ending in ToDsc() cannot be followed by operators other than Submit()..
        /// </summary>
        internal static string ToDscUsedIncorrectly {
            get {
                return ResourceManager.GetString("ToDscUsedIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries ending in ToHdfs() cannot be followed by operators other than Submit()..
        /// </summary>
        internal static string ToHdfsUsedIncorrectly {
            get {
                return ResourceManager.GetString("ToHdfsUsedIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Too many elements before reduction..
        /// </summary>
        internal static string TooManyElementsBeforeReduction {
            get {
                return ResourceManager.GetString("TooManyElementsBeforeReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method should not be tagged with both HomomorphicAttribute and LeftHomomorphicAttribute..
        /// </summary>
        internal static string TooManyHomomorphicAttributes {
            get {
                return ResourceManager.GetString("TooManyHomomorphicAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many items in collection..
        /// </summary>
        internal static string TooManyItems {
            get {
                return ResourceManager.GetString("TooManyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0} doesn&apos;t contain field/property {1}.
        /// </summary>
        internal static string TypeDoesNotContainMember {
            get {
                return ResourceManager.GetString("TypeDoesNotContainMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain a field named {1}.
        /// </summary>
        internal static string TypeDoesNotContainRequestedField {
            get {
                return ResourceManager.GetString("TypeDoesNotContainRequestedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialized types must have at least one data member. Type={0}..
        /// </summary>
        internal static string TypeMustHaveDataMembers {
            get {
                return ResourceManager.GetString("TypeMustHaveDataMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto-serialize a type containing pointers. Type = {0}. .
        /// </summary>
        internal static string TypeNotSerializable {
            get {
                return ResourceManager.GetString("TypeNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot auto-serialize a type that is not public. Type = {0}..
        /// </summary>
        internal static string TypeRequiredToBePublic {
            get {
                return ResourceManager.GetString("TypeRequiredToBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for type with private field. Type = {0}..
        /// </summary>
        internal static string UDTHasFieldOfNonPublicType {
            get {
                return ResourceManager.GetString("UDTHasFieldOfNonPublicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for delegate type. Type = {0}..
        /// </summary>
        internal static string UDTIsDelegateType {
            get {
                return ResourceManager.GetString("UDTIsDelegateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-serialization is not supported for type that is an abstract type or has generic arguments which are abstract types. Type = {0}..
        /// </summary>
        internal static string UDTMustBeConcreteType {
            get {
                return ResourceManager.GetString("UDTMustBeConcreteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected job status: {0}..
        /// </summary>
        internal static string UnexpectedJobStatus {
            get {
                return ResourceManager.GetString("UnexpectedJobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: LINQ to HPC query expression cannot be handled : {0}..
        /// </summary>
        internal static string UnhandledQuery {
            get {
                return ResourceManager.GetString("UnhandledQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown channel kind: {0}..
        /// </summary>
        internal static string UnknownChannelType {
            get {
                return ResourceManager.GetString("UnknownChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown channel of type: {0}..
        /// </summary>
        internal static string UnknownChannelType2 {
            get {
                return ResourceManager.GetString("UnknownChannelType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown compression scheme..
        /// </summary>
        internal static string UnknownCompressionScheme {
            get {
                return ResourceManager.GetString("UnknownCompressionScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection type: {0}..
        /// </summary>
        internal static string UnknownConnectionType {
            get {
                return ResourceManager.GetString("UnknownConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown method in expression to summarize: {0}..
        /// </summary>
        internal static string UnknownMethodInExpression {
            get {
                return ResourceManager.GetString("UnknownMethodInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider {0} is unknown. Register it using DataProvider.Register..
        /// </summary>
        internal static string UnknownProvier {
            get {
                return ResourceManager.GetString("UnknownProvier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: This parameter expression didn&apos;t have a name..
        /// </summary>
        internal static string UnnamedParameterExpression {
            get {
                return ResourceManager.GetString("UnnamedParameterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized data source: {0}..
        /// </summary>
        internal static string UnrecognizedDataSource {
            get {
                return ResourceManager.GetString("UnrecognizedDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized operator name: {0}..
        /// </summary>
        internal static string UnrecognizedOperatorName {
            get {
                return ResourceManager.GetString("UnrecognizedOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected execution kind..
        /// </summary>
        internal static string UnsupportedExecutionKind {
            get {
                return ResourceManager.GetString("UnsupportedExecutionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type {0} is not supported..
        /// </summary>
        internal static string UnsupportedExpressionsType {
            get {
                return ResourceManager.GetString("UnsupportedExpressionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of type {0} is not supported for expression-summarization..
        /// </summary>
        internal static string UnsupportedExpressionType {
            get {
                return ResourceManager.GetString("UnsupportedExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler type not supported: {0}..
        /// </summary>
        internal static string UnsupportedSchedulerType {
            get {
                return ResourceManager.GetString("UnsupportedSchedulerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The non-generic methods CreateQuery() and Execute() are not supported.  Use CreateQuery&lt;T&gt;() and Execute&lt;T&gt;() instead..
        /// </summary>
        internal static string UntypedProviderMethodsNotSupported {
            get {
                return ResourceManager.GetString("UntypedProviderMethodsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VertexBridge arguments are malformed. argsString={0}.
        /// </summary>
        internal static string VertexBridgeBadArgs {
            get {
                return ResourceManager.GetString("VertexBridgeBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window size must be greater than 1..
        /// </summary>
        internal static string WindowSizeMustyBeGTOne {
            get {
                return ResourceManager.GetString("WindowSizeMustyBeGTOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteByte is not supported..
        /// </summary>
        internal static string WriteByteNotSupported {
            get {
                return ResourceManager.GetString("WriteByteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error returned from WriteFile: {0}..
        /// </summary>
        internal static string WriteFileError {
            get {
                return ResourceManager.GetString("WriteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write is not supported..
        /// </summary>
        internal static string WriteNotSupported {
            get {
                return ResourceManager.GetString("WriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Wrong combination of flags..
        /// </summary>
        internal static string WrongFlagCombination {
            get {
                return ResourceManager.GetString("WrongFlagCombination", resourceCulture);
            }
        }
    }
}
